services:
  db:
    image: postgres:15
    container_name: orchestrator_db_container
    environment:
      # These define the user/pass INSIDE the database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: